spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online__shop
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081